# Generated by Django 5.2.17 on 2026-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='densidad',
            field=models.CharField(choices=[('compacta', 'Compacta'), ('normal', 'Normal'), ('comoda', 'Cómoda')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='claro', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vista_preferida',
            field=models.CharField(choices=[('kanban', 'Kanban'), ('lista', 'Lista')], default='kanban', max_length=10),
        ),
    ]
