# Generated by Django 5.2.17 on 2026-08-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_densidad_usuario_tema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'permissions': [('gestionar_entidades', 'Crear y editar entidades contratantes')], 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('gestionar_usuarios', 'Administrar perfiles y usuarios')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
