# Generated by Django 5.2.17 on 2026-08-18 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='auth.group')),
            ],
            options={
                'verbose_name': 'Información de perfil',
                'verbose_name_plural': 'Información de perfiles',
            },
        ),
    ]
