# Generated by Django 5.2.17 on 2026-08-14 03:56

import django.core.validators
import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_proceso', models.CharField(db_index=True, help_text='Número SECOP o referencia interna.', max_length=120)),
                ('objeto', models.TextField()),
                ('modalidad', models.CharField(blank=True, choices=[('licitacion', 'Licitación pública'), ('seleccion_abreviada', 'Selección abreviada'), ('concurso_meritos', 'Concurso de méritos'), ('minima_cuantia', 'Mínima cuantía'), ('contratacion_directa', 'Contratación directa'), ('subasta_inversa', 'Subasta inversa'), ('privada', 'Invitación privada'), ('otra', 'Otra')], max_length=30)),
                ('url_secop', models.URLField(blank=True)),
                ('origen', models.CharField(choices=[('manual', 'Capturado manualmente'), ('importado', 'Importado de Excel'), ('secop', 'API SECOP II'), ('ia', 'Extraído por IA'), ('regla', 'Regla determinista')], default='manual', max_length=20)),
                ('presupuesto_oficial', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('plazo_ejecucion_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_limite_observaciones', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_adjudicacion', models.DateField(blank=True, null=True)),
                ('fechas_verificadas_en', models.DateTimeField(blank=True, null=True)),
                ('estado', django_fsm.FSMField(choices=[('detectado', 'Detectado'), ('en_evaluacion', 'En evaluación'), ('descartado', 'Descartado'), ('apto', 'Apto — decisión de participar'), ('en_preparacion', 'En preparación'), ('presentado', 'Presentado'), ('adjudicado', 'Adjudicado'), ('no_adjudicado', 'No adjudicado'), ('desierto', 'Declarado desierto'), ('suspendido', 'Suspendido')], db_index=True, default='detectado', max_length=50, protected=True)),
                ('motivo_descarte', models.TextField(blank=True)),
                ('resumen_ejecutivo', models.TextField(blank=True)),
                ('semaforo', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], max_length=10)),
                ('codigos_unspsc', models.ManyToManyField(blank=True, related_name='procesos', to='core.codigounspsc')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='core.entidad')),
                ('fechas_verificadas_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_fechas_verificadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('seguidores', models.ManyToManyField(blank=True, help_text='Chatter: reciben notificaciones del proceso.', related_name='procesos_seguidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cierre'],
                'indexes': [models.Index(fields=['estado', 'fecha_cierre'], name='procesos_pr_estado_265f13_idx'), models.Index(fields=['entidad', '-creado_en'], name='procesos_pr_entidad_31584a_idx')],
                'constraints': [models.UniqueConstraint(fields=('entidad', 'numero_proceso'), name='uq_proceso_entidad_numero')],
            },
        ),
    ]
