# Generated by Django 5.2.17 on 2026-08-14 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionDocumental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('proyecto', 'Proyecto de pliego'), ('definitivo', 'Pliego definitivo'), ('adenda', 'Adenda'), ('respuesta_obs', 'Respuesta a observaciones'), ('anexo', 'Anexo técnico'), ('cronograma', 'Modificación de cronograma')], max_length=20)),
                ('secuencia', models.PositiveSmallIntegerField(help_text='Orden cronológico dentro del proceso. 0 = documento inicial.')),
                ('numero_adenda', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('resumen_cambios', models.TextField(blank=True, help_text='Qué modificó respecto a la versión anterior.')),
                ('procesada', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Versión documental',
                'verbose_name_plural': 'Versiones documentales',
                'ordering': ['proceso', 'secuencia'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('juridico', 'Jurídico'), ('financiero', 'Financiero'), ('tecnico', 'Técnico'), ('experiencia', 'Experiencia'), ('organizacional', 'Capacidad organizacional'), ('puntuable', 'Factor de puntuación')], db_index=True, max_length=20)),
                ('numeral', models.CharField(blank=True, help_text='Ej: 3.2.1 — para trazabilidad al pliego.', max_length=40)),
                ('descripcion', models.TextField()),
                ('indicador', models.CharField(blank=True, help_text='Ej: indice_liquidez, razon_endeudamiento, capacidad_residual.', max_length=60)),
                ('operador', models.CharField(blank=True, choices=[('>=', '≥'), ('<=', '≤'), ('=', '='), ('>', '>'), ('<', '<')], max_length=4)),
                ('valor_umbral', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unidad', models.CharField(blank=True, help_text='COP, SMMLV, años, veces…', max_length=20)),
                ('origen', models.CharField(choices=[('manual', 'Capturado manualmente'), ('importado', 'Importado de Excel'), ('secop', 'API SECOP II'), ('ia', 'Extraído por IA'), ('regla', 'Regla determinista')], default='ia', max_length=20)),
                ('cita_pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('cita_texto', models.TextField(blank=True, help_text='Fragmento literal que sustenta el requisito.')),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('cumplimiento', models.CharField(choices=[('por_verificar', 'Por verificar'), ('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('parcial', 'Cumple parcialmente'), ('subsanable', 'No cumple pero es subsanable'), ('no_aplica', 'No aplica')], db_index=True, default='por_verificar', max_length=20)),
                ('justificacion', models.TextField(blank=True)),
                ('es_critico', models.BooleanField(default=False, help_text='Su incumplimiento causa rechazo.')),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='procesos.proceso')),
                ('reemplaza', models.OneToOneField(blank=True, help_text='Requisito de una versión anterior que este deroga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazado_por', to='procesos.requisito')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitos_verificados', to=settings.AUTH_USER_MODEL)),
                ('version_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_introducidos', to='procesos.versiondocumental')),
            ],
            options={
                'ordering': ['tipo', 'numeral'],
            },
        ),
        migrations.AddConstraint(
            model_name='versiondocumental',
            constraint=models.UniqueConstraint(fields=('proceso', 'secuencia'), name='uq_version_proceso_secuencia'),
        ),
        migrations.AddIndex(
            model_name='requisito',
            index=models.Index(fields=['proceso', 'tipo', 'cumplimiento'], name='procesos_re_proceso_603500_idx'),
        ),
    ]
