# Generated by Django 5.2.17 on 2026-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_versiondocumental_requisito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='analisis_en_curso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceso',
            name='analisis_pagina_actual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='analisis_paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='confianza_ia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='lectura_ia',
            field=models.TextField(blank=True, help_text='1-2 frases de lectura del modelo.'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='puntaje_ajuste',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-100. Lo calcula un AnalisisIA de tipo TRIAGE.', null=True),
        ),
    ]
