# Generated by Django 5.2.17 on 2026-08-14 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_proceso_analisis_en_curso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('exp_direccionada', 'Experiencia posiblemente direccionada'), ('specs_marca', 'Especificaciones atadas a marca'), ('plazo_irreal', 'Plazo de ejecución irreal'), ('garantia_despro', 'Garantías desproporcionadas'), ('indic_restrictivos', 'Indicadores financieros restrictivos'), ('anticipo', 'Anticipo sin amortización clara'), ('multas', 'Régimen sancionatorio agresivo'), ('cronograma_corto', 'Tiempo insuficiente para preparar'), ('presupuesto_bajo', 'Presupuesto por debajo de mercado'), ('pago_diferido', 'Condiciones de pago desfavorables')], max_length=30)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('descripcion', models.TextField()),
                ('cita_numeral', models.CharField(blank=True, max_length=40)),
                ('cita_pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('manual', 'Capturado manualmente'), ('importado', 'Importado de Excel'), ('secop', 'API SECOP II'), ('ia', 'Extraído por IA'), ('regla', 'Regla determinista')], default='ia', max_length=20)),
                ('descartado_por_usuario', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='procesos.proceso')),
                ('version_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos', to='procesos.versiondocumental')),
            ],
            options={
                'ordering': ['-severidad'],
            },
        ),
    ]
