# Generated by Django 5.2.17 on 2026-08-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_riesgo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proceso',
            options={'ordering': ['-fecha_cierre'], 'permissions': [('ver_procesos', 'Ver procesos'), ('crear_procesos', 'Crear procesos manualmente'), ('editar_procesos', 'Editar datos de un proceso'), ('eliminar_procesos', 'Eliminar procesos'), ('mover_etapa', 'Mover procesos entre etapas del flujo'), ('descartar_procesos', 'Descartar procesos'), ('verificar_fechas', 'Marcar datos como verificados'), ('ver_todos', 'Ver procesos de todo el equipo'), ('importar_procesos', 'Importar desde Excel')]},
        ),
    ]
