# Generated by Django 5.2.17 on 2026-08-14 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procesos', '0002_versiondocumental_requisito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('reunion', 'Reunión'), ('tarea', 'Tarea'), ('revision', 'Revisión de documentos'), ('envio', 'Envío / radicación')], default='tarea', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('vence_en', models.DateTimeField(db_index=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('evento_calendar_id', models.CharField(blank=True, help_text='ID en Google Calendar si se sincroniza.', max_length=200)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='procesos.proceso')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'ordering': ['vence_en'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuerpo', models.TextField()),
                ('adjunto', models.FileField(blank=True, upload_to='comentarios/%Y/%m/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('menciones', models.ManyToManyField(blank=True, related_name='comentarios_mencionado', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='procesos.proceso')),
                ('responde_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='social.comentario')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('cierre_proximo', 'Cierre próximo'), ('nueva_adenda', 'Nueva adenda publicada'), ('analisis_listo', 'Análisis de IA listo'), ('riesgo_alto', 'Riesgo alto detectado'), ('mencion', 'Te mencionaron'), ('asignacion', 'Proceso asignado'), ('no_cumple', 'Requisito crítico no cumplido')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(blank=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('email_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='procesos.proceso')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['destinatario', 'leida_en'], name='social_aler_destina_5d5636_idx')],
            },
        ),
    ]
